### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by alexvb** [daugsbi/simpleen-cli#2]
Hi,

I'm trying to translate a JSON with a single key. `yarn run simpleen translate` always failes with an unhandled promise rejection:

Translation source:

```json
{
  "test.hello": "Hello"
}
```

simpleen.config.json:

```json
{
    "source_language": "DE",
    "target_languages": [
        "EN-US"
    ],
    "interpolation": "i18n",
    "input_path": "./in/*.json",
    "output_path": "./out/$FILE.json",
    "auth_key": "MY_AUTH_KEY"
}
```

Error:

```
⠼ Translate 1/1 DE => EN-US
✖ Translate 1/1 DE => EN-US
(node:43440) UnhandledPromiseRejectionWarning: Error: 500 - Request failed Request failed with status code 500
    at Task.task (/...PATH/node_modules/simpleen/lib/commands/translate.js:52:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by daugsbi** [comment]
Sorry, we were running out of credits. Just increased it, can you retry?

Thanks for mentioning :+1:

**Comment by alexvb** [comment]
Thank you for the quick fix. It seems to be working now 👍 

While testing, I noticed that emojis in source strings will lead to request errors too.

**Comment by daugsbi** [comment]
You can now use your Emojis in source strings. :+1: :partying_face: :rocket:

The problem was the config for the database connection (utf8mb4).
